# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\yunus\OneDrive\Desktop\atmproject\deneme\account.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_accountScreen(object):
    def setupUi(self, accountScreen):
        accountScreen.setObjectName("accountScreen")
        accountScreen.resize(551, 516)
        accountScreen.setStyleSheet("background-color: qconicalgradient(cx:0.5, cy:0.5, angle:0, stop:0 rgba(35, 40, 3, 255), stop:0.16 rgba(136, 106, 22, 255), stop:0.225 rgba(166, 140, 41, 255), stop:0.285 rgba(204, 181, 74, 255), stop:0.345 rgba(235, 219, 102, 255), stop:0.415 rgba(245, 236, 112, 255), stop:0.52 rgba(209, 190, 76, 255), stop:0.57 rgba(187, 156, 51, 255), stop:0.635 rgba(168, 142, 42, 255), stop:0.695 rgba(202, 174, 68, 255), stop:0.75 rgba(218, 202, 86, 255), stop:0.815 rgba(208, 187, 73, 255), stop:0.88 rgba(187, 156, 51, 255), stop:0.935 rgba(137, 108, 26, 255), stop:1 rgba(35, 40, 3, 255));")
        accountScreen.setIconSize(QtCore.QSize(500, 500))
        self.centralwidget = QtWidgets.QWidget(accountScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(10, 230, 81, 71))
        self.pushButton_8.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.pushButton_8.setText("")
        icon = QtGui.QIcon()
        filelog = os.getcwd()
        icon.addPixmap(QtGui.QPixmap(f"{filelog}\\atmproject\\atm_proje_file\\icns\\money.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon)
        self.pushButton_8.setIconSize(QtCore.QSize(50, 100))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(410, 230, 81, 71))
        self.pushButton_7.setStyleSheet("font: 18pt \".AppleSystemUIFont\";\n"
"background-color: rgb(230, 230, 230);\n"
"font: 14pt \".AppleSystemUIFont\";")
        self.pushButton_7.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(f"{filelog}\\atmproject\\atm_proje_file\\icns\\money-withdrawal.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon1)
        self.pushButton_7.setIconSize(QtCore.QSize(50, 100))
        self.pushButton_7.setObjectName("pushButton_7")
        self.return_button = QtWidgets.QPushButton(self.centralwidget)
        self.return_button.setGeometry(QtCore.QRect(170, 330, 181, 71))
        self.return_button.setStyleSheet("background-color: rgb(64, 128, 2);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(f"{filelog}\\atmproject\\atm_proje_file\\icns\\reply.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.return_button.setIcon(icon2)
        self.return_button.setIconSize(QtCore.QSize(70, 70))
        self.return_button.setObjectName("return_button")
        self.check_button = QtWidgets.QPushButton(self.centralwidget)
        self.check_button.setGeometry(QtCore.QRect(100, 120, 131, 41))
        self.check_button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(230, 230, 230);")
        self.check_button.setObjectName("check_button")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(410, 110, 81, 61))
        self.pushButton_2.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.pushButton_2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(f"{filelog}\\atmproject\\atm_proje_file\\icns\\transaction.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon3)
        self.pushButton_2.setIconSize(QtCore.QSize(70, 70))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 110, 71, 61))
        self.pushButton_3.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.pushButton_3.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(f"{filelog}\\atmproject\\atm_proje_file\\icns\\debit-card.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon4)
        self.pushButton_3.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_3.setObjectName("pushButton_3")
        self.insert_button = QtWidgets.QPushButton(self.centralwidget)
        self.insert_button.setGeometry(QtCore.QRect(100, 240, 141, 41))
        self.insert_button.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.insert_button.setObjectName("insert_button")
        self.withdraw_button = QtWidgets.QPushButton(self.centralwidget)
        self.withdraw_button.setGeometry(QtCore.QRect(260, 240, 141, 41))
        self.withdraw_button.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.withdraw_button.setObjectName("withdraw_button")
        self.statement_button = QtWidgets.QPushButton(self.centralwidget)
        self.statement_button.setGeometry(QtCore.QRect(260, 120, 131, 41))
        self.statement_button.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.statement_button.setObjectName("statement_button")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(150, 10, 201, 51))
        self.lineEdit.setStyleSheet("background-color: rgb(204, 204, 204);\n"
"font: 36pt \".AppleSystemUIFont\";")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(120, 80, 261, 21))
        self.lineEdit_2.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        accountScreen.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(accountScreen)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 551, 24))
        self.menubar.setObjectName("menubar")
        accountScreen.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(accountScreen)
        self.statusbar.setObjectName("statusbar")
        accountScreen.setStatusBar(self.statusbar)

        self.retranslateUi(accountScreen)
        QtCore.QMetaObject.connectSlotsByName(accountScreen)

    def retranslateUi(self, accountScreen):
        _translate = QtCore.QCoreApplication.translate
        accountScreen.setWindowTitle(_translate("accountScreen", "account"))
        self.return_button.setText(_translate("accountScreen", "RETURN MENU"))
        self.check_button.setText(_translate("accountScreen", "CHECK BALANCE"))
        self.insert_button.setText(_translate("accountScreen", "INSERT MONEY"))
        self.withdraw_button.setText(_translate("accountScreen", "WITHDRAW MONEY"))
        self.statement_button.setText(_translate("accountScreen", "STATEMENT"))
        self.lineEdit.setText(_translate("accountScreen", " WELCOME"))
        self.lineEdit_2.setText(_translate("accountScreen", "CLICK FOR ACCOUNT TRANSACTIONS"))
